project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - slides.qmd
  execute:
    freeze: auto

website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Slides"
        href: slides.qmd