project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - paper.qmd
    - slides.qmd

execute:
  freeze: auto

website:
  site-url: https://robinlovelace.net/reproducible-project-template/
  title: "Reproducible Project Template"
  repo-url: https://github.com/Robinlovelace/reproducible-project-template
  repo-branch: main
  repo-actions: [edit, issue]
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Slides"
        href: slides.qmd
    right:
      - icon: github
        href: https://github.com/Robinlovelace/reproducible-project-template
        aria-label: GitHub